baseURL = "https://adotinthevoid.github.io/"
title = "Nixon Enraght-Moony"
theme = "my-hyde"

[params]
description = "Rust and other joys"
themeColor = "theme-base-0b"
# layoutReverse = true
copyright = { text = "Some Rights Reserved", link = "meta/#copyright" }

[Menus]
main = [
    { Name = "Blog", URL = "/posts" },
    { Name = "Github", URL = "https://github.com/adotinthevoid/" },
    { Name = "LinkedIn", URL = "https://www.linkedin.com/in/nixon-enraght-moony-b68587187/" }
]

[permalinks]
posts = "/posts/:year/:month/:title/"

[markup.highlight]
codeFences = true
guessSyntax = false
noClasses = true
style = "monokailight" # dracula monokailight
tabWidth = 4

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
